Feature roberto crear album
robertoamin/Aplicacion_movil_vinilos pull request #70
Opened 2023-05-04 04:15 UTC by robertoamin

se agrega nueva funcionalidad de crear Album

2023-05-05 13:58 UTC, AndresFUlloa approved these changes

2023-05-05 14:23 UTC, jaPardor1 approved these changes

2023-05-05 14:29 UTC, JesusDiazDiaz requested changes

2023-05-05 14:29 UTC, JesusDiazDiaz commented on app/src/main/res/layout/fragment_album_item_list.xml
> +            app:srcCompat="@drawable/ic_plus_24"/>
El icono que esta usando ic_plus_24, es toda una imagen del boton, deberia ser solo el plus

2023-05-05 14:29 UTC, JesusDiazDiaz commented on app/src/main/res/layout/activity_album_crear.xml
> +            app:helperText="Ingrese el nombre del álbum"
Esto debe ir en el archivo de string y no aqui

2023-05-05 14:29 UTC, JesusDiazDiaz commented on app/src/main/res/layout/activity_album_crear.xml
> +            android:text="Crear Álbum"
Esto debe ir en el archivo de string y no aqui

2023-05-05 14:29 UTC, JesusDiazDiaz commented on app/src/main/res/layout/activity_album_crear.xml
> +            app:helperText="Ingrese una descripción para el álbum"
Esto debe ir en el archivo de string y no aqui

2023-05-05 14:29 UTC, JesusDiazDiaz commented on app/src/main/res/layout/activity_album_crear.xml
> +            app:helperText="Ingrese la URL de la portada del álbum"
Esto debe ir en el archivo de string y no aqui

2023-05-05 14:29 UTC, JesusDiazDiaz commented on app/src/main/res/layout/activity_album_crear.xml
> +            app:helperText="Ingrese la fecha de lanzamiento del álbum"
Esto debe ir en el archivo de string y no aqui

2023-05-05 14:29 UTC, JesusDiazDiaz commented on app/src/main/res/layout/activity_album_crear.xml
> +            app:helperText="Ingrese el género del álbum"
Esto debe ir en el archivo de string y no aqui

2023-05-05 14:29 UTC, JesusDiazDiaz commented on app/src/main/res/layout/activity_album_crear.xml
> +            app:helperText="Ingrese la discográfica del álbum"
Esto debe ir en el archivo de string y no aqui

2023-05-05 14:29 UTC, JesusDiazDiaz commented on app/src/main/res/layout/activity_album_crear.xml
> +                    android:text="Guardar"
Esto debe ir en el archivo de string y no aqui

2023-05-05 14:29 UTC, JesusDiazDiaz commented on app/src/main/res/layout/activity_album_crear.xml
> +                    android:text="Cancelar"
Esto debe ir en el archivo de string y no aqui

2023-05-07 15:45 UTC, JesusDiazDiaz approved these changes

2023-05-07 15:54 UTC, AndresFUlloa approved these changes

2023-05-07 16:19 UTC, robertoamin commented on app/src/main/res/layout/activity_album_crear.xml
> +            app:helperText="Ingrese la discográfica del álbum"
hecho

2023-05-07 16:19 UTC, robertoamin commented on app/src/main/res/layout/activity_album_crear.xml
> +            app:helperText="Ingrese el género del álbum"
hecho

2023-05-07 16:19 UTC, robertoamin commented on app/src/main/res/layout/activity_album_crear.xml
> +            app:helperText="Ingrese la URL de la portada del álbum"
hecho

2023-05-07 16:19 UTC, robertoamin commented on app/src/main/res/layout/activity_album_crear.xml
> +            app:helperText="Ingrese una descripción para el álbum"
hecho

2023-05-07 16:19 UTC, robertoamin commented on app/src/main/res/layout/activity_album_crear.xml
> +            app:helperText="Ingrese el nombre del álbum"
hecho

2023-05-07 16:19 UTC, robertoamin commented on app/src/main/res/layout/fragment_album_item_list.xml
> +            app:srcCompat="@drawable/ic_plus_24"/>
hecho

2023-05-07 16:19 UTC, robertoamin commented on app/src/main/res/layout/activity_album_crear.xml
> +                    android:text="Cancelar"
hecho

2023-05-07 16:19 UTC, robertoamin commented on app/src/main/res/layout/activity_album_crear.xml
> +                    android:text="Guardar"
hecho

2023-05-07 16:19 UTC, merged